<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- SENSORS -->
    <xacro:property name="lidar_rad" value="0.038"/>
    <xacro:property name="lidar_width" value="0.0335"/>
    <xacro:property name="lidar_material" value="black"/>
    <xacro:property name="lidar_mass" value="0.042"/>

    <!-- LIDAR LINK -->
    <link name="lidar_frame">
        <visual>
            <geometry>
                <cylinder radius="${lidar_rad}" length="${lidar_width}"/>
            </geometry>
            <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0"/>
            <material name="${lidar_material}"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${lidar_rad}" length="${lidar_width}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${chassis_hight + lidar_width / 2}" rpy="0.0 0.0 0.0"/>
        </collision>

        <xacro:inertial_cylinder mass="${lidar_mass}" radius="${lidar_rad}" length="${lidar_width}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_frame"/>
        <origin xyz="0.0 0.0 ${chassis_hight + lidar_width / 2}" rpy="0.0 0.0 0.0"/>
    </joint>


    <gazebo reference="lidar_frame">
        <sensor name='lidar_frame' type='gpu_lidar'>
            <gz_frame_id>lidar_frame</gz_frame_id>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <pose relative_to='lidar_frame'>0 0 0 0 0 0</pose>
            <topic>scan</topic>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>12.0</max>
                    <resolution>0.05</resolution>
                </range>
            </lidar>

            <plugin
                filename="gz-sim-sensors-system"
                name="gz::sim::systems::Sensors">
                <render_engine>ogre2</render_engine>
            </plugin>
        </sensor>
    </gazebo>

</robot>
