<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- LIDAR LINK -->
    <link name="imu_frame">
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="imu_frame"/>
        <origin xyz="${chassis_width / 2} 0.0 ${chassis_hight / 2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="imu_frame">

        <sensor name="imu_sensor" type="imu">
            <always_on>1</always_on>
            <update_rate>60</update_rate>
            <visualize>true</visualize>
            <topic>imu</topic>


            <plugin filename="gz-sim-imu-system"
                    name="gz::sim::systems::Imu">
            </plugin>
        </sensor>


    </gazebo>

</robot>
