<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- INCLUDES -->
    <xacro:include filename="material.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- CHASSIS PROPERTIES -->
    <xacro:property name="chassis_width" value="0.5" />
    <xacro:property name="chassis_length" value="0.65" />
    <xacro:property name="chassis_hight" value="0.3" />
    <xacro:property name="chassis_shift" value="${chassis_length/2}" />
    <xacro:property name="chassis_mass" value="39" />

    <!-- WHEEL PROPERTIES -->
    <xacro:property name="wheel_rad" value="0.1" />
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_material" value="orange"/>
    <xacro:property name="wheel_mass" value="2.5"/>

    <!-- STEERING LIMITS PROPERTIES -->
    <xacro:property name="steering_max_angle" value="0.52"/>        <!--rad-->
    <xacro:property name="steering_max_speed" value="1.0"/>         <!--rad/s-->
    <xacro:property name="steering_max_torque" value="10.0"/>       <!-- N.m-->


    <!-- BASE LINK -->
    <link name="base_link">
    </link>

    <!-- BASE FOOTPRINT LINK -->
    <link name ="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- CHASSIS LINK -->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_hight}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="${chassis_length/2} 0.0 ${chassis_hight/2}" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_hight}"/>
            </geometry>
            <origin xyz="${chassis_length/2} 0.0 ${chassis_hight/2}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_hight}">
            <origin xyz="${chassis_length/2} 0.0 ${chassis_hight/2}" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${-chassis_shift} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <!-- LEFT WHEEL LINK -->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_rad}" length="${wheel_width}">
            <origin xyz="0.0 ${wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${chassis_length / 2} ${chassis_width / 2} 0.0" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- RIGHT WHEEL LINK -->
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${-wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${-wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_rad}" length="${wheel_width}">
            <origin xyz="0.0 ${-wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${chassis_length / 2} ${-chassis_width / 2} 0.0" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- REAR CASTER WHEEL LINK -->
    <link name="rear_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_rad}"/>
            </geometry>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_rad}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_rad}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="rear_caster_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="rear_caster_wheel_link"/>
        <origin xyz="${chassis_length / 6} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="rear_caster_wheel_link">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


    <!-- FRONT CASTER WHEEL LINK -->
    <link name="front_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_rad}"/>
            </geometry>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_rad}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_rad}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="front_caster_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${chassis_length * 4 / 5} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="front_caster_wheel_link">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>