<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- INCLUDES -->
    <xacro:include filename="material.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- CHASSIS PROPERTIES -->
    <xacro:property name="chassis_width" value="0.3" />
    <xacro:property name="chassis_hight" value="0.15" />
    <xacro:property name="chassis_shift" value="0.1" />
    <xacro:property name="chassis_mass" value="0.5" />

    <!-- WHEEL PROPERTIES -->
    <xacro:property name="wheel_rad" value="0.05" />
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_material" value="orange"/>
    <xacro:property name="wheel_mass" value="0.1"/>



    <!-- BASE LINK -->
    <link name="base_link">
    </link>

    <!-- CHASSIS LINK -->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_width} ${chassis_width} ${chassis_hight}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="${chassis_width/2} 0.0 ${chassis_hight/2}" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_width} ${chassis_width} ${chassis_hight}"/>
            </geometry>
            <origin xyz="${chassis_width/2} 0.0 ${chassis_hight/2}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_width}" y="${chassis_width}" z="${chassis_hight}">
            <origin xyz="${chassis_width/2} 0.0 ${chassis_hight/2}" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${-chassis_shift} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <!-- LEFT WHEEL LINK -->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_rad}" length="${wheel_width}">
            <origin xyz="0.0 ${wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 ${chassis_width / 2} 0.0" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- RIGHT WHEEL LINK -->
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${-wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_rad}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0.0 ${-wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_rad}" length="${wheel_width}">
            <origin xyz="0.0 ${-wheel_width / 2} 0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 ${-chassis_width / 2} 0.0" rpy="0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- CASTER WHEEL LINK -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_rad}"/>
            </geometry>
            <material name="${wheel_material}"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_rad}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${wheel_mass}" radius="${wheel_rad}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${chassis_width * 3 / 4} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference="caster_wheel_link">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>